language:
- python
python:
- '2.7'
before_install:
- sudo apt-get install -y curl tar
- eval export AWS_ACCESS_KEY_ID=\$${TRAVIS_BRANCH}_aws_access_key_id
- eval export AWS_SECRET_ACCESS_KEY=\$${TRAVIS_BRANCH}_aws_secret_access_key
- eval export AWS_REGION=\$${TRAVIS_BRANCH}_aws_region
install:
- pip install coveralls
script: 
- coverage run test-setup.py test
after_success:
- coveralls
